[package]
name = "prek_pty"
version = "0.0.1"
edition = { workspace = true }

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
rustix = { version = "1.0.8", features = ["pty", "process", "fs", "termios"] }
tokio = {  workspace = true }
