[package]
name = "prek_yaml"
version = "0.0.1"
edition.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
serde_yaml = { workspace = true }
thiserror = { workspace = true }
